#!/bin/sh
set -eu
here="$(dirname "${0}")"
root="${1}"
platform="${2}"

build_recipe() {
envsubst <<EOF
version: 1

AppDir:
  path: ${APPDIR_PATH}

  app_info:
    id: ${APPDIR_APPINFO_ID}
    name: ${APPDIR_APPINFO_NAME}
    version: ${APPDIR_APPINFO_VERSION}
    icon: ${APPDIR_APPINFO_ICON}
    exec: ${APPDIR_APPINFO_EXEC}
    exec_args: ${APPDIR_APPINFO_EXEC_ARGS}

  apt:
    arch:
    - ${APPDIR_APT_ARCH}
    sources:
    - sourceline: deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ ${APPDIR_APT_SOURCES_DISTRIBUTION} main
      key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x${APPDIR_APT_SOURCES_PUBKEY}
    - sourceline: deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ ${APPDIR_APT_SOURCES_DISTRIBUTION}-updates main
      key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x${APPDIR_APT_SOURCES_PUBKEY}
    - sourceline: deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu/ ${APPDIR_APT_SOURCES_DISTRIBUTION}-security main
      key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x${APPDIR_APT_SOURCES_PUBKEY}
    - sourceline: deb [arch=arm64,armhf] http://ports.ubuntu.com/ubuntu-ports/ ${APPDIR_APT_SOURCES_DISTRIBUTION} main
      key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x${APPDIR_APT_SOURCES_PUBKEY}
    - sourceline: deb [arch=arm64,armhf] http://ports.ubuntu.com/ubuntu-ports/ ${APPDIR_APT_SOURCES_DISTRIBUTION}-updates main
      key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x${APPDIR_APT_SOURCES_PUBKEY}
    - sourceline: deb [arch=arm64,armhf] http://ports.ubuntu.com/ubuntu-ports/ ${APPDIR_APT_SOURCES_DISTRIBUTION}-security main
      key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x${APPDIR_APT_SOURCES_PUBKEY}
    include: ${APPDIR_APT_INCLUDE}

AppImage:
  arch: ${APPIMAGE_ARCH}
EOF
}

find "${root}" -mindepth 1 -maxdepth 1 -type d | while read -r path; do
  if [ -z "${APPIMAGE_ICON-}" ]; then
    icon_path="${path}/usr/share/icons/hicolor/scalable/mimetypes"
    icon_name=no-icon
    mkdir -p "${icon_path}"
    touch "${icon_path}/${icon_name}.svg"
  fi

  if [ ! -e *.AppImage.zsync ]; then
    touch dummy-to-prevent-fail-of-appimage-builder.AppImage.zsync
  fi

  set -a
  APPIMAGE_ARCH="$(basename "${path}")"
  APPDIR_PATH="${path}"
  APPDIR_APPINFO_ID="${APPIMAGE_ID}"
  APPDIR_APPINFO_NAME="${APPIMAGE_NAME}"
  APPDIR_APPINFO_VERSION="${APPIMAGE_VERSION}"
  APPDIR_APPINFO_ICON="${APPIMAGE_ICON:-${icon_name}}"
  APPDIR_APPINFO_EXEC="${APPIMAGE_EXEC:-usr/bin/${APPIMAGE_NAME}}"
  APPDIR_APPINFO_EXEC_ARGS="${APPIMAGE_EXEC_ARGS:-\$@}"
  APPDIR_APT_ARCH="${platform#*/}"
  APPDIR_APT_SOURCES_DISTRIBUTION="${UBUNTU_RELEASE}"
  APPDIR_APT_SOURCES_PUBKEY="${UBUNTU_PUBKEY}"
  APPDIR_APT_INCLUDE="[${APPIMAGE_DEPS}]"
  build_recipe >AppImageBuilder.yml
done


