name: Create GitHub Release

env:
  RUNTIME_DEPENDENCIES: '[ libudev1, libevdev2, libglib2.0-0, libgee-0.8-2, upower ]'
  UBUNTU_RELEASE: jammy
  UBUNTU_PUBKEY: 871920D1991BC93C

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          platforms: ${{ matrix.platform }}
          outputs: build
          build-args: |
            UBUNTU_RELEASE=${{ env.UBUNTU_RELEASE }}
      - name: Prepare AppImage build
        shell: bash
        env:
          TARGET_PLATFORM: ${{ matrix.platform }}
        run: |
          set -eu

          mkdir -p AppDir
          find build -mindepth 1 -maxdepth 1 -type d | while read -r path; do
            cp -a "${path}" AppDir/usr
            build_arch="$(basename "${path}")"
          done

          icon_path=AppDir/usr/share/icons/hicolor/scalable/mimetypes
          icon_name=no-icon
          mkdir -p "${icon_path}"
          touch "${icon_path}/${icon_name}.svg"

          touch dummy-to-prevent-fail-of-appimage-builder.AppImage.zsync

          set -a
          APPIMAGE_ARCH="${build_arch}"
          APPDIR_APPINFO_ID="$(echo "${GITHUB_REPOSITORY}" | tr / .)"
          APPDIR_APPINFO_NAME="${GITHUB_REPOSITORY##*/}"
          APPDIR_APPINFO_VERSION="${GITHUB_REF_NAME}"
          APPDIR_APPINFO_ICON="${icon_name}"
          APPDIR_APPINFO_EXEC="usr/bin/${APPDIR_APPINFO_NAME}"
          APPDIR_APPINFO_EXEC_ARGS='$@'
          APPDIR_APT_ARCH="${TARGET_PLATFORM#*/}"
          APPDIR_APT_SOURCES_DISTRIBUTION="${UBUNTU_RELEASE}"
          APPDIR_APT_SOURCES_PUBKEY="${UBUNTU_PUBKEY}"
          APPDIR_APT_INCLUDE="${RUNTIME_DEPENDENCIES}"
          envsubst <AppImageBuilder.template.yml >AppImageBuilder.yml
      - uses: AppImageCrafters/build-appimage@v1
      - uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            build
            !build/provenance.json
            *.AppImage

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-output
      - shell: bash
        run: |
          mkdir -p assets
          cp -a ./*.AppImage assets
          find build -mindepth 1 -maxdepth 1 -type d -printf '%P\n' | while read -r arch; do
            cd "${GITHUB_WORKSPACE}/build/${arch}"
            tar -czf "${GITHUB_WORKSPACE}/assets/${GITHUB_REPOSITORY##*/}-${GITHUB_REF_NAME}-${arch}.tar.gz" *
            cd -
          done
      - run: |
          algo="${SHA_ALGORITHM:-256}"
          find assets -type f | while read -r asset; do
            shasum --binary --algorithm "${algo}" "${asset}" >"${asset}.sha${algo}"
          done
        shell: bash
      - uses: softprops/action-gh-release@v1
        with:
          files: assets/*
